# Generated by Django 4.1.1 on 2022-09-14 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nfc', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NFC',
        ),
    ]
